-- Drops claude_views.v_quickbooks_match_suggestions from the application
-- database.
--
-- Background: the claude_views.* read-only views are intended to live only
-- on the Neon read-only mirror consumed by GET /api/ops-dashboard. A copy
-- of v_quickbooks_match_suggestions ended up on the application database as
-- well, and Postgres treats the view as a hard dependency on every column
-- it selects. That dependency was blocking deploy-time schema sync from
-- making any change to public.quickbooks_match_suggestions (the deploy
-- attempted ALTER TABLE ... DROP COLUMN "rejected_at" and Postgres refused
-- with "other objects depend on it").
--
-- Dropping the view here is safe:
--   * The /api/ops-dashboard endpoint reads from the Neon mirror
--     (a different host), not from this database, so the dashboard
--     continues to work.
--   * No application code in this repo selects from claude_views.* on the
--     application database.
--
-- Conservative scope: only the one view that surfaced as a blocker is
-- removed. If sibling views in the same schema later block another deploy,
-- a follow-up migration should drop them by name so each removal is
-- explicit and auditable.

DROP VIEW IF EXISTS claude_views.v_quickbooks_match_suggestions;
