-- Priorities Phase 3: soft-delete, templates, saved views, review cadence.
-- Auto-generated by drizzle-kit, then stripped of project_document_links
-- duplication (that table is already created by 0068_project_document_links;
-- drizzle's diff included it only because the matching meta snapshot for
-- 0068 was never committed).
--
-- Adds (see PR #937):
--   - priority_saved_views table        (Phase C.3)
--   - priority_templates table          (Phase C.2)
--   - mytool_company_priorities columns:
--       deleted_at          (Phase B.1 — soft-delete/archive)
--       review_cadence_days (Phase C.4 — SLA cadence)
--       last_reviewed_at    (Phase C.4)
--       last_reviewed_by_user_id (Phase C.4)
--
-- Corresponding hand-written migrations 0069/0070/0071/0072 from earlier
-- in the PR have been replaced by this single drizzle-generated file so
-- the schema-drift CI guard (db-check) can verify schema = snapshot.

CREATE TABLE "priority_saved_views" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"name" text NOT NULL,
	"active_tab" text DEFAULT 'my' NOT NULL,
	"scope" text,
	"department_key" text,
	"level_filter" text,
	"health_filter" text,
	"search_query" text,
	"show_closed" boolean DEFAULT false NOT NULL,
	"show_archived" boolean DEFAULT false NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "priority_saved_views_user_name_unique" UNIQUE("user_id","name")
);
--> statement-breakpoint
CREATE TABLE "priority_templates" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"title_template" text NOT NULL,
	"body_template" text,
	"scope_default" text DEFAULT 'role' NOT NULL,
	"severity_default" text DEFAULT 'normal' NOT NULL,
	"horizon_default" text DEFAULT 'week' NOT NULL,
	"department_key" text,
	"target_outcome" text,
	"definition_of_done" text,
	"next_action" text,
	"owner_role" text,
	"created_by_user_id" integer,
	"deleted_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "mytool_company_priorities" ADD COLUMN "deleted_at" timestamp;--> statement-breakpoint
ALTER TABLE "mytool_company_priorities" ADD COLUMN "review_cadence_days" integer;--> statement-breakpoint
ALTER TABLE "mytool_company_priorities" ADD COLUMN "last_reviewed_at" timestamp;--> statement-breakpoint
ALTER TABLE "mytool_company_priorities" ADD COLUMN "last_reviewed_by_user_id" integer;--> statement-breakpoint
ALTER TABLE "priority_saved_views" ADD CONSTRAINT "priority_saved_views_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "priority_templates" ADD CONSTRAINT "priority_templates_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mytool_company_priorities" ADD CONSTRAINT "mytool_company_priorities_last_reviewed_by_user_id_users_id_fk" FOREIGN KEY ("last_reviewed_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_priorities_deleted_at" ON "mytool_company_priorities" USING btree ("deleted_at") WHERE "deleted_at" IS NULL;--> statement-breakpoint
CREATE INDEX "idx_priority_templates_dept" ON "priority_templates" USING btree ("department_key") WHERE "deleted_at" IS NULL;--> statement-breakpoint
CREATE INDEX "idx_priority_templates_live" ON "priority_templates" USING btree ("deleted_at");--> statement-breakpoint
CREATE INDEX "idx_priority_saved_views_user" ON "priority_saved_views" USING btree ("user_id","sort_order");
