-- Migration: Convert global unique constraints on project_name and external_ref
-- to partial unique indexes WHERE deleted_at IS NULL.
-- This allows soft-deleted rows to be re-created with the same key.
-- Date: 2026-04-13

BEGIN;

-- 1. Drop the existing global unique constraint on project_info.project_name
-- The constraint name is auto-generated by Drizzle as "project_info_project_name_unique"
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'project_info_project_name_unique'
      AND conrelid = 'project_info'::regclass
  ) THEN
    ALTER TABLE project_info DROP CONSTRAINT project_info_project_name_unique;
  END IF;
END $$;

-- Create partial unique index for active (non-deleted) rows only
CREATE UNIQUE INDEX IF NOT EXISTS uq_project_info_project_name_active
  ON project_info(project_name)
  WHERE deleted_at IS NULL;

-- 2. Drop the existing global unique constraint on work_items.external_ref
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'work_items_external_ref_unique'
      AND conrelid = 'work_items'::regclass
  ) THEN
    ALTER TABLE work_items DROP CONSTRAINT work_items_external_ref_unique;
  END IF;
END $$;

-- Create partial unique index for active (non-deleted) rows only
CREATE UNIQUE INDEX IF NOT EXISTS uq_work_items_external_ref_active
  ON work_items(external_ref)
  WHERE deleted_at IS NULL;

COMMIT;
