import type { Express } from 'express';
import type { Server } from 'http';
import { registerRoutes as registerLegacyRoutes } from '../routes';
import { registerTemplateGovernanceRoutes } from './template-governance-routes';
import { registerQuickBooksRoutes } from '../quickbooks-routes';
import { registerQuickBooksInvoiceMatchRoutes } from './quickbooks-invoice-matches.routes';
import { registerFinanceTrustRoutes } from './finance-trust-routes';
import { registerFinanceLinesRoutes } from './finance-lines.routes';
import { registerFinanceVoImpactRoutes } from './finance-vo-impact.routes';
import { registerPdIntakeRoutes } from './pd-intake.routes';
import { registerImpactRoutes } from './impact.routes';
import { registerEmailLinksRoutes } from './email-links.routes';
import { registerScreenSettingsRoutes } from './admin-screen-settings.routes';
import { registerExceptionDashboardRoutes } from './exception-dashboard.routes';
import { registerDocumentManagementRoutes } from './document-management.routes';
import { registerDocumentCommentsRoutes } from './document-comments.routes';
import { registerDocumentManagementAdminRoutes } from './document-management-admin.routes';
import { registerDocumentProvisioningRoutes } from './document-provisioning.routes';
import { registerDocumentFilesRoutes } from './document-files.routes';
import { registerManagedDocumentApprovalRoutes } from './managed-document-approvals.routes';
import { registerDocumentReadinessRoutes } from './document-readiness.routes';
import { registerProjectDocumentRegisterRoutes } from './project-document-register.routes';
import { registerTrackerReplicaRoutes } from './tracker-replica.routes';
import { registerExcelVsAppRoutes } from './excel-vs-app.routes';
import { registerReconciliationRoutes } from './reconciliation.routes';
import { registerQbReconRoutes } from './qb-recon.routes';
import { registerQbProjectMatchRoutes } from './qb-project-match.routes';
import { registerQualityTasksRoutes } from './quality-tasks.routes';
import { registerStandupSessionsRoutes } from './standup-sessions.routes';
import { registerDeliveryMilestonesRoutes } from './delivery-milestones.routes';
import { registerMyQueueRoutes } from './my-queue.routes';
import { registerImportConfigRoutes } from './import-config.routes';
import { registerSmartImportReviewRoutes } from './smart-import-review.routes';
import { registerCosLineReviewRoutes } from './cos-line-review.routes';
import { registerCashflowWorklistsRoutes } from './cashflow-worklists.routes';
import { registerFinanceHealthRoutes } from './finance-health.routes';
import { registerExecutionBoardRoutes } from './execution-board.routes';
import { financeErrorTracker } from '../middleware/finance-error-tracker';

export async function registerRoutes(httpServer: Server, app: Express) {
  // Observe finance 5xx responses for the error-rate monitor (read-only).
  app.use(financeErrorTracker);
  registerFinanceHealthRoutes(app);
  registerExecutionBoardRoutes(app);
  registerTemplateGovernanceRoutes(app);
  registerQuickBooksRoutes(app);
  registerQuickBooksInvoiceMatchRoutes(app);
  registerFinanceTrustRoutes(app);
  registerFinanceLinesRoutes(app);
  registerCashflowWorklistsRoutes(app);
  registerFinanceVoImpactRoutes(app);
  registerPdIntakeRoutes(app);
  // registerControlledDocumentRoutes(app); — retired in D6 Phase 5.
  registerImpactRoutes(app);
  registerEmailLinksRoutes(app);
  registerScreenSettingsRoutes(app);
  registerExceptionDashboardRoutes(app);
  registerDocumentManagementRoutes(app);
  registerDocumentCommentsRoutes(app);
  registerDocumentManagementAdminRoutes(app);
  registerDocumentProvisioningRoutes(app);
  registerDocumentFilesRoutes(app);
  registerManagedDocumentApprovalRoutes(app);
  registerDocumentReadinessRoutes(app);
  registerProjectDocumentRegisterRoutes(app);
  registerTrackerReplicaRoutes(app);
  registerExcelVsAppRoutes(app);
  registerReconciliationRoutes(app);
  registerQbReconRoutes(app);
  registerQbProjectMatchRoutes(app);
  registerQualityTasksRoutes(app);
  registerStandupSessionsRoutes(app);
  registerDeliveryMilestonesRoutes(app);
  registerMyQueueRoutes(app);
  registerImportConfigRoutes(app);
  registerSmartImportReviewRoutes(app);
  registerCosLineReviewRoutes(app);
  return registerLegacyRoutes(httpServer, app);
}
