import { db } from "./db";
import { eq } from "drizzle-orm";
import { mockSpItems } from "@shared/schema";

const MOCK_ITEMS = [
  {
    mockItemId: "mock-1",
    fields: {
      Title: "Acme Solar Corp",
      Client: "Acme Solar Corp",
      DueDate: "2026-03-15",
      Request_x0020_Type: "First Assessment",
      Priority: "High",
      Status: "In Progress",
      Number_x0020_of_x0020_Reworks: 0,
      Project_x0020_Developer: { LookupValue: "John van der Merwe", Email: "john@acmesolar.co.za" },
      Designer: { LookupValue: "Tanaka Moyo", Email: "tanaka@emergent.energy" },
      Size_x0020_in_x0020_kWp: 250,
      Province: "Gauteng",
      GPS: "-26.2041, 28.0473",
      Funding_x0020_Type: "PPA",
      Bills_x002f_Tariff_x0020_data: "Received",
      Metering_x0020_data: "Pending meter install",
      Site_x0020_inspection_x0020_form: "",
      Comments: "Initial assessment underway. Client responsive.",
      Working_x0020_schedule: "Mon-Fri 07:00-17:00",
      Batteries_x0020_needed: "Yes",
      Battery_x0020_Size: "100kWh",
      Diesel_x0020_Gen_x0020_integration_x0020_needed: "No",
      Roof_x0020_replacement_x0020_needed: "No",
      HSE_x0020_Discussed: "Yes",
      ClickUpSynced: "No",
      Days_x0020_in_x0020_progress: 12,
    },
  },
  {
    mockItemId: "mock-2",
    fields: {
      Title: "Acme Solar Corp",
      Client: "Acme Solar Corp",
      DueDate: "2026-04-01",
      Request_x0020_Type: "Cost Proposal",
      Priority: "High",
      Status: "Awaiting CP",
      Number_x0020_of_x0020_Reworks: 1,
      Project_x0020_Developer: { LookupValue: "John van der Merwe", Email: "john@acmesolar.co.za" },
      Designer: { LookupValue: "Dean Fourie", Email: "dean@emergent.energy" },
      Size_x0020_in_x0020_kWp: 250,
      Province: "Gauteng",
      GPS: "-26.2041, 28.0473",
      Funding_x0020_Type: "PPA",
      Comments: "CP draft v2 issued. Awaiting PD feedback on exclusions.",
      Working_x0020_schedule: "Mon-Fri 07:00-17:00",
      Batteries_x0020_needed: "Yes",
      Battery_x0020_Size: "100kWh",
      Days_x0020_in_x0020_progress: 28,
    },
  },
  {
    mockItemId: "mock-3",
    fields: {
      Title: "GreenFields Mining",
      Client: "GreenFields Mining",
      DueDate: "2026-02-28",
      Request_x0020_Type: "Site Visit Report",
      Priority: "Urgent",
      Status: "In Progress",
      Number_x0020_of_x0020_Reworks: 0,
      Project_x0020_Developer: { LookupValue: "Sarah Nkosi", Email: "sarah@greenfields.co.za" },
      Designer: { LookupValue: "Tanaka Moyo", Email: "tanaka@emergent.energy" },
      Size_x0020_in_x0020_kWp: 500,
      Province: "Limpopo",
      GPS: "-23.9045, 29.4689",
      Funding_x0020_Type: "Cash",
      Comments: "Site visit scheduled for next week. Need to confirm access arrangements.",
      Working_x0020_schedule: "Mon-Sat 06:00-18:00",
      Batteries_x0020_needed: "TBD",
      Diesel_x0020_Gen_x0020_integration_x0020_needed: "Yes",
      Roof_x0020_replacement_x0020_needed: "TBD",
      HSE_x0020_Discussed: "No",
      Days_x0020_in_x0020_progress: 5,
    },
  },
  {
    mockItemId: "mock-4",
    fields: {
      Title: "Sunshine Retail Group",
      Client: "Sunshine Retail Group",
      DueDate: "2026-03-10",
      Request_x0020_Type: "Meter Installation",
      Priority: "Medium",
      Status: "In Progress",
      Number_x0020_of_x0020_Reworks: 0,
      Project_x0020_Developer: { LookupValue: "Peter Botha", Email: "peter@sunshine.co.za" },
      Designer: { LookupValue: "Tanaka Moyo", Email: "tanaka@emergent.energy" },
      Size_x0020_in_x0020_kWp: 120,
      Province: "Western Cape",
      GPS: "-33.9249, 18.4241",
      Funding_x0020_Type: "Rental",
      Metering_x0020_data: "No existing meter",
      Comments: "Meter procurement in progress.",
      Batteries_x0020_needed: "No",
      Days_x0020_in_x0020_progress: 8,
    },
  },
  {
    mockItemId: "mock-5",
    fields: {
      Title: "TechPark Developments",
      Client: "TechPark Developments",
      DueDate: "2026-03-20",
      Request_x0020_Type: "Data Analysis Request",
      Priority: "Low",
      Status: "In Progress",
      Number_x0020_of_x0020_Reworks: 0,
      Project_x0020_Developer: { LookupValue: "Lisa Chen", Email: "lisa@techpark.co.za" },
      Designer: { LookupValue: "Dean Fourie", Email: "dean@emergent.energy" },
      Size_x0020_in_x0020_kWp: 75,
      Province: "KwaZulu-Natal",
      Funding_x0020_Type: "Lease",
      Bills_x002f_Tariff_x0020_data: "Received - 12 months",
      Metering_x0020_data: "Smart meter installed",
      Comments: "Analysing load profile data. Good data quality.",
      Days_x0020_in_x0020_progress: 3,
    },
  },
  {
    mockItemId: "mock-6",
    fields: {
      Title: "BlueSky Logistics",
      Client: "BlueSky Logistics",
      DueDate: "2026-04-15",
      Request_x0020_Type: "Sizing Rational Request",
      Priority: "Medium",
      Status: "New",
      Number_x0020_of_x0020_Reworks: 0,
      Project_x0020_Developer: { LookupValue: "David Molefe", Email: "david@bluesky.co.za" },
      Designer: { LookupValue: "Tanaka Moyo", Email: "tanaka@emergent.energy" },
      Size_x0020_in_x0020_kWp: 180,
      Province: "Gauteng",
      GPS: "-26.1076, 28.0567",
      Funding_x0020_Type: "PPA, Rental",
      Comments: "",
      Days_x0020_in_x0020_progress: 0,
    },
  },
  {
    mockItemId: "mock-7",
    fields: {
      Title: "GreenFields Mining",
      Client: "GreenFields Mining",
      DueDate: "2026-05-01",
      Request_x0020_Type: "First Assessment",
      Priority: "High",
      Status: "In Progress",
      Number_x0020_of_x0020_Reworks: 0,
      Project_x0020_Developer: { LookupValue: "Sarah Nkosi", Email: "sarah@greenfields.co.za" },
      Designer: { LookupValue: "Dean Fourie", Email: "dean@emergent.energy" },
      Size_x0020_in_x0020_kWp: 800,
      Province: "Limpopo",
      Funding_x0020_Type: "Cash",
      Comments: "Second site - warehouse complex. Large rooftop area available.",
      Working_x0020_schedule: "24/7 operations",
      Batteries_x0020_needed: "Yes",
      Battery_x0020_Size: "500kWh",
      Diesel_x0020_Gen_x0020_integration_x0020_needed: "Yes",
      HSE_x0020_Discussed: "Yes",
      Days_x0020_in_x0020_progress: 2,
    },
  },
  {
    mockItemId: "mock-8",
    fields: {
      Title: "FreshFoods Distribution",
      Client: "FreshFoods Distribution",
      DueDate: "2026-02-15",
      Request_x0020_Type: "Cost Proposal",
      Priority: "Critical",
      Status: "Blocked",
      Number_x0020_of_x0020_Reworks: 3,
      Project_x0020_Developer: { LookupValue: "Anna Schmidt", Email: "anna@freshfoods.co.za" },
      Designer: { LookupValue: "Tanaka Moyo", Email: "tanaka@emergent.energy" },
      Size_x0020_in_x0020_kWp: 350,
      Province: "Eastern Cape",
      Funding_x0020_Type: "PPA",
      Comments: "BLOCKED: Awaiting structural engineer report. Client escalated urgency.",
      Working_x0020_schedule: "Mon-Fri 06:00-20:00, Sat 06:00-14:00",
      Batteries_x0020_needed: "Yes",
      Battery_x0020_Size: "200kWh",
      Roof_x0020_replacement_x0020_needed: "Yes",
      Days_x0020_in_x0020_progress: 45,
    },
  },
  {
    mockItemId: "mock-9",
    fields: {
      Title: "EcoHotel Cape Town",
      Client: "EcoHotel Cape Town",
      DueDate: "2026-03-25",
      Request_x0020_Type: "First Assessment",
      Priority: "Medium",
      Status: "In Progress",
      Number_x0020_of_x0020_Reworks: 0,
      Project_x0020_Developer: { LookupValue: "Michael du Plessis", Email: "michael@ecohotel.co.za" },
      Designer: { LookupValue: "Dean Fourie", Email: "dean@emergent.energy" },
      Size_x0020_in_x0020_kWp: 95,
      Province: "Western Cape",
      GPS: "-33.9181, 18.4233",
      Funding_x0020_Type: "Rental",
      Bills_x002f_Tariff_x0020_data: "Received",
      Comments: "Small commercial. Tourism sector - aesthetics important.",
      Batteries_x0020_needed: "No",
      Diesel_x0020_Gen_x0020_integration_x0020_needed: "No",
      Days_x0020_in_x0020_progress: 6,
    },
  },
  {
    mockItemId: "mock-10",
    fields: {
      Title: "Mpumalanga Agri Co-op",
      Client: "Mpumalanga Agri Co-op",
      DueDate: "2026-04-30",
      Request_x0020_Type: "Site Visit Report",
      Priority: "Low",
      Status: "In Progress",
      Number_x0020_of_x0020_Reworks: 0,
      Project_x0020_Developer: { LookupValue: "Themba Dlamini", Email: "themba@mpuagri.co.za" },
      Designer: { LookupValue: "Tanaka Moyo", Email: "tanaka@emergent.energy" },
      Size_x0020_in_x0020_kWp: 1200,
      Province: "Mpumalanga",
      Funding_x0020_Type: "Cash",
      Comments: "Large agricultural installation. Remote location - access road may need work.",
      Working_x0020_schedule: "Seasonal - contact before visit",
      Batteries_x0020_needed: "TBD",
      Battery_x0020_Size: "",
      Diesel_x0020_Gen_x0020_integration_x0020_needed: "TBD",
      Roof_x0020_replacement_x0020_needed: "No",
      HSE_x0020_Discussed: "No",
      Days_x0020_in_x0020_progress: 1,
    },
  },
  {
    mockItemId: "mock-11",
    fields: {
      Title: "Acme Solar Corp",
      Client: "Acme Solar Corp",
      DueDate: "2026-05-15",
      Request_x0020_Type: "Site Visit Report",
      Priority: "Medium",
      Status: "New",
      Number_x0020_of_x0020_Reworks: 0,
      Project_x0020_Developer: { LookupValue: "John van der Merwe", Email: "john@acmesolar.co.za" },
      Designer: { LookupValue: "Tanaka Moyo", Email: "tanaka@emergent.energy" },
      Size_x0020_in_x0020_kWp: 250,
      Province: "Gauteng",
      GPS: "-26.2041, 28.0473",
      Funding_x0020_Type: "PPA",
      Comments: "Pre-construction site visit needed.",
      Days_x0020_in_x0020_progress: 0,
    },
  },
  {
    mockItemId: "mock-12",
    fields: {
      Title: "Sunshine Retail Group",
      Client: "Sunshine Retail Group",
      DueDate: "2026-06-01",
      Request_x0020_Type: "First Assessment",
      Priority: "High",
      Status: "In Progress",
      Number_x0020_of_x0020_Reworks: 0,
      Project_x0020_Developer: { LookupValue: "Peter Botha", Email: "peter@sunshine.co.za" },
      Designer: { LookupValue: "Dean Fourie", Email: "dean@emergent.energy" },
      Size_x0020_in_x0020_kWp: 400,
      Province: "Western Cape",
      GPS: "",
      Funding_x0020_Type: "Rental",
      Comments: "Second branch - larger facility. GPS coordinates TBD.",
      Batteries_x0020_needed: "TBD",
      Days_x0020_in_x0020_progress: 4,
    },
  },
];

export async function seedMockSpItems(): Promise<number> {
  await db.delete(mockSpItems);

  for (const item of MOCK_ITEMS) {
    await db.insert(mockSpItems).values({
      mockItemId: item.mockItemId,
      fields: item.fields,
      etag: `"mock-etag-${item.mockItemId}-v1"`,
      createdDateTime: new Date(Date.now() - Math.random() * 30 * 86400000).toISOString(),
      lastModifiedDateTime: new Date().toISOString(),
    });
  }

  return MOCK_ITEMS.length;
}

export async function resetMockSpItems(): Promise<number> {
  return seedMockSpItems();
}

export async function simulateExternalEdit(
  mockItemId: string,
  fieldEdits: Record<string, any>,
): Promise<void> {
  const [item] = await db.select().from(mockSpItems)
    .where(eq(mockSpItems.mockItemId, mockItemId));

  if (!item) throw new Error(`Mock item ${mockItemId} not found`);

  const currentFields = item.fields as Record<string, any>;
  const updatedFields = { ...currentFields, ...fieldEdits };

  await db.update(mockSpItems)
    .set({
      fields: updatedFields,
      lastModifiedDateTime: new Date().toISOString(),
      etag: `"mock-etag-${mockItemId}-v${Date.now()}"`,
      updatedAt: new Date(),
    })
    .where(eq(mockSpItems.mockItemId, mockItemId));
}

export { MOCK_ITEMS };
