import { and, desc, eq, inArray, isNull, sql } from "drizzle-orm";
import {
  invoiceDescriptionPatterns,
  invoicePatternRules,
  quickbooksDocuments,
  quickbooksMatchSuggestions,
  type QuickBooksMatchSuggestion,
} from "@shared/schema";
import { db } from "../db";

function parseJsonColumn<T>(value: unknown, fallback: T): T {
  if (typeof value !== "string") return (value ?? fallback) as T;
  try {
    return JSON.parse(value) as T;
  } catch {
    return fallback;
  }
}

export interface CreateSuggestionInput {
  scope: string;
  qbRealmId: string;
  appEntityId: number | null;
  appEntityLabel: string | null;
  candidates: unknown;
  requestedBy: number | null;
  acceptedAt?: Date | null;
  acceptedBy?: number | null;
  acceptedQbId?: string | null;
  manualOverride?: boolean;
  autoGenerated?: boolean;
}

export interface SuggestionStatusProjection {
  id: number;
  scope: string;
  appEntityId: number | null;
  acceptedAt: Date | null;
  rejectedAt: Date | null;
}

export interface PendingAutoSuggestionRow {
  id: number;
  scope: string;
  appEntityId: number | null;
  appEntityLabel: string | null;
  candidates: unknown;
  requestedAt: Date;
}

export interface NumberRuleRow {
  id: number;
  patternType: string;
  patternValue: string;
  confidenceWeight: string | null;
}

export interface DescriptionRuleRow {
  id: number;
  tokenSet: unknown;
  confidenceWeight: string | null;
}

export class QuickBooksInvoiceMatchesRepository {
  private _dbInstance?: typeof db;

  constructor(dbInstance?: typeof db) {
    this._dbInstance = dbInstance;
  }

  private get dbInstance(): typeof db {
    return this._dbInstance || db;
  }

  // ── quickbooks_match_suggestions ──

  async createSuggestion(values: CreateSuggestionInput): Promise<{ id: number }> {
    const [created] = await this.dbInstance
      .insert(quickbooksMatchSuggestions)
      .values({
        scope: values.scope,
        qbRealmId: values.qbRealmId,
        appEntityId: values.appEntityId,
        appEntityLabel: values.appEntityLabel,
        candidates: values.candidates as object,
        requestedBy: values.requestedBy,
        acceptedAt: values.acceptedAt ?? null,
        acceptedBy: values.acceptedBy ?? null,
        acceptedQbId: values.acceptedQbId ?? null,
        manualOverride: values.manualOverride ?? false,
        autoGenerated: values.autoGenerated ?? false,
      })
      .returning({ id: quickbooksMatchSuggestions.id });
    return { id: created.id };
  }

  async getSuggestionById(id: number): Promise<QuickBooksMatchSuggestion | null> {
    const [row] = await this.dbInstance
      .select()
      .from(quickbooksMatchSuggestions)
      .where(eq(quickbooksMatchSuggestions.id, id))
      .limit(1);
    return row ? ({ ...row, candidates: parseJsonColumn(row.candidates, []) } as QuickBooksMatchSuggestion) : null;
  }

  async getSuggestionStatusById(id: number): Promise<SuggestionStatusProjection | null> {
    const [row] = await this.dbInstance
      .select({
        id: quickbooksMatchSuggestions.id,
        scope: quickbooksMatchSuggestions.scope,
        appEntityId: quickbooksMatchSuggestions.appEntityId,
        acceptedAt: quickbooksMatchSuggestions.acceptedAt,
        rejectedAt: quickbooksMatchSuggestions.rejectedAt,
      })
      .from(quickbooksMatchSuggestions)
      .where(eq(quickbooksMatchSuggestions.id, id))
      .limit(1);
    return row ?? null;
  }

  async markAccepted(
    id: number,
    args: { qbEntityId: string; confidence: number; decidedByUserId: number | null },
  ): Promise<void> {
    await this.dbInstance
      .update(quickbooksMatchSuggestions)
      .set({
        acceptedAt: new Date(),
        acceptedBy: args.decidedByUserId,
        acceptedQbId: args.qbEntityId,
        acceptedConfidence: String(args.confidence) as unknown as never,
      })
      .where(eq(quickbooksMatchSuggestions.id, id));
  }

  async markRejected(
    id: number,
    args: { reason: string; decidedByUserId: number | null },
  ): Promise<void> {
    await this.dbInstance
      .update(quickbooksMatchSuggestions)
      .set({
        rejectedAt: new Date(),
        rejectedBy: args.decidedByUserId,
        rejectionReason: args.reason,
      })
      .where(eq(quickbooksMatchSuggestions.id, id));
  }

  async listAppEntityIdsWithPendingSuggestion(
    scope: string,
    appEntityIds: number[],
  ): Promise<Set<number>> {
    if (appEntityIds.length === 0) return new Set();
    const rows = await this.dbInstance
      .select({ appEntityId: quickbooksMatchSuggestions.appEntityId })
      .from(quickbooksMatchSuggestions)
      .where(
        and(
          eq(quickbooksMatchSuggestions.scope, scope),
          inArray(quickbooksMatchSuggestions.appEntityId, appEntityIds),
          isNull(quickbooksMatchSuggestions.acceptedAt),
          isNull(quickbooksMatchSuggestions.rejectedAt),
        ),
      );
    const out = new Set<number>();
    for (const r of rows) {
      if (r.appEntityId !== null) out.add(r.appEntityId);
    }
    return out;
  }

  async listPendingAutoSuggestions(limit: number): Promise<PendingAutoSuggestionRow[]> {
    const rows = await this.dbInstance
      .select({
        id: quickbooksMatchSuggestions.id,
        scope: quickbooksMatchSuggestions.scope,
        appEntityId: quickbooksMatchSuggestions.appEntityId,
        appEntityLabel: quickbooksMatchSuggestions.appEntityLabel,
        candidates: quickbooksMatchSuggestions.candidates,
        requestedAt: quickbooksMatchSuggestions.requestedAt,
      })
      .from(quickbooksMatchSuggestions)
      .where(
        and(
          eq(quickbooksMatchSuggestions.autoGenerated, true),
          isNull(quickbooksMatchSuggestions.acceptedAt),
          isNull(quickbooksMatchSuggestions.rejectedAt),
        ),
      )
      .orderBy(desc(quickbooksMatchSuggestions.requestedAt))
      .limit(limit);
    return rows.map((row: any) => ({ ...row, candidates: parseJsonColumn(row.candidates, []) }));
  }

  // ── quickbooks_documents ──

  async getQbDocumentId(
    qbEntityId: string,
    qbRealmId: string,
    qbEntityType: string,
  ): Promise<number | null> {
    const [row] = await this.dbInstance
      .select({ id: quickbooksDocuments.id })
      .from(quickbooksDocuments)
      .where(
        and(
          eq(quickbooksDocuments.qbEntityId, qbEntityId),
          eq(quickbooksDocuments.qbRealmId, qbRealmId),
          eq(quickbooksDocuments.qbEntityType, qbEntityType),
          isNull(quickbooksDocuments.deletedAt),
        ),
      )
      .limit(1);
    return row?.id ?? null;
  }

  async updateQbDocumentBalance(
    id: number,
    balance: number | null,
    paymentStatus: string | null,
  ): Promise<void> {
    await this.dbInstance
      .update(quickbooksDocuments)
      .set({
        qbBalance: balance !== null ? (String(balance) as unknown as never) : null,
        qbPaymentStatus: paymentStatus,
        updatedAt: new Date(),
      })
      .where(eq(quickbooksDocuments.id, id));
  }

  // ── invoice_pattern_rules + invoice_description_patterns ──

  async listActiveNumberRulesByCounterparty(
    counterpartyId: number,
  ): Promise<NumberRuleRow[]> {
    return this.dbInstance
      .select({
        id: invoicePatternRules.id,
        patternType: invoicePatternRules.patternType,
        patternValue: invoicePatternRules.patternValue,
        confidenceWeight: invoicePatternRules.confidenceWeight,
      })
      .from(invoicePatternRules)
      .where(
        and(
          eq(invoicePatternRules.counterpartyId, counterpartyId),
          eq(invoicePatternRules.isActive, true),
          isNull(invoicePatternRules.deletedAt),
        ),
      );
  }

  async listActiveDescriptionRulesByCounterparty(
    counterpartyId: number,
  ): Promise<DescriptionRuleRow[]> {
    return this.dbInstance
      .select({
        id: invoiceDescriptionPatterns.id,
        tokenSet: invoiceDescriptionPatterns.tokenSet,
        confidenceWeight: invoiceDescriptionPatterns.confidenceWeight,
      })
      .from(invoiceDescriptionPatterns)
      .where(
        and(
          eq(invoiceDescriptionPatterns.counterpartyId, counterpartyId),
          eq(invoiceDescriptionPatterns.isActive, true),
          isNull(invoiceDescriptionPatterns.deletedAt),
        ),
      );
  }

  async listCounterpartiesWithActiveRules(): Promise<number[]> {
    const [numberRows, descriptionRows] = await Promise.all([
      this.dbInstance
        .selectDistinct({ counterpartyId: invoicePatternRules.counterpartyId })
        .from(invoicePatternRules)
        .where(
          and(
            eq(invoicePatternRules.isActive, true),
            isNull(invoicePatternRules.deletedAt),
          ),
        ),
      this.dbInstance
        .selectDistinct({ counterpartyId: invoiceDescriptionPatterns.counterpartyId })
        .from(invoiceDescriptionPatterns)
        .where(
          and(
            eq(invoiceDescriptionPatterns.isActive, true),
            isNull(invoiceDescriptionPatterns.deletedAt),
          ),
        ),
    ]);
    const ids = new Set<number>();
    for (const r of numberRows) if (r.counterpartyId !== null) ids.add(r.counterpartyId);
    for (const r of descriptionRows) if (r.counterpartyId !== null) ids.add(r.counterpartyId);
    return Array.from(ids);
  }

  async incrementNumberRuleCounter(
    ids: number[],
    outcome: "approved" | "rejected",
  ): Promise<void> {
    if (ids.length === 0) return;
    if (outcome === "approved") {
      await this.dbInstance
        .update(invoicePatternRules)
        .set({
          timesConfirmed: sql`${invoicePatternRules.timesConfirmed} + 1`,
          timesMatched: sql`${invoicePatternRules.timesMatched} + 1`,
          lastConfirmedAt: new Date(),
        })
        .where(inArray(invoicePatternRules.id, ids));
    } else {
      await this.dbInstance
        .update(invoicePatternRules)
        .set({
          timesOverridden: sql`${invoicePatternRules.timesOverridden} + 1`,
          timesMatched: sql`${invoicePatternRules.timesMatched} + 1`,
        })
        .where(inArray(invoicePatternRules.id, ids));
    }
  }

  async incrementDescriptionRuleCounter(
    ids: number[],
    outcome: "approved" | "rejected",
  ): Promise<void> {
    if (ids.length === 0) return;
    const now = new Date();
    if (outcome === "approved") {
      await this.dbInstance
        .update(invoiceDescriptionPatterns)
        .set({
          timesConfirmed: sql`${invoiceDescriptionPatterns.timesConfirmed} + 1`,
          timesMatched: sql`${invoiceDescriptionPatterns.timesMatched} + 1`,
          lastConfirmedAt: now,
          updatedAt: now,
        })
        .where(inArray(invoiceDescriptionPatterns.id, ids));
    } else {
      await this.dbInstance
        .update(invoiceDescriptionPatterns)
        .set({
          timesOverridden: sql`${invoiceDescriptionPatterns.timesOverridden} + 1`,
          timesMatched: sql`${invoiceDescriptionPatterns.timesMatched} + 1`,
          updatedAt: now,
        })
        .where(inArray(invoiceDescriptionPatterns.id, ids));
    }
  }
}
