-- Auto-generated: pre-create all enums and stub tables before drizzle-kit push
-- This prevents interactive prompts that block CI/CD automation

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'meeting_action_item_status') THEN CREATE TYPE meeting_action_item_status AS ENUM ('pending', 'converted', 'dismissed'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'approval_status') THEN CREATE TYPE approval_status AS ENUM ('pending', 'approved', 'rejected'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'audit_source') THEN CREATE TYPE audit_source AS ENUM ('UI', 'IMPORT', 'SETTINGS', 'DOCS', 'SYSTEM'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'pm_action_type') THEN CREATE TYPE pm_action_type AS ENUM ('site_visit', 'generate_po', 'link_invoice', 'raise_variation', 'log_delay', 'log_risk', 'upload_photo', 'update_progress', 'escalate'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'pm_action_status') THEN CREATE TYPE pm_action_status AS ENUM ('pending', 'approved', 'rejected', 'completed'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'pm_safety_status') THEN CREATE TYPE pm_safety_status AS ENUM ('clear', 'issue_open'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ms_object_type') THEN CREATE TYPE ms_object_type AS ENUM ('email', 'event', 'teams', 'sharepoint_file'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ms_account_status') THEN CREATE TYPE ms_account_status AS ENUM ('active', 'disconnected', 'expired'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'communication_follow_up_status') THEN CREATE TYPE communication_follow_up_status AS ENUM ('pending', 'completed', 'dismissed'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'standup_cadence') THEN CREATE TYPE standup_cadence AS ENUM ('DAILY', 'EVERY_2_DAYS', 'EVERY_3_DAYS', 'WEEKLY'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'standup_mood') THEN CREATE TYPE standup_mood AS ENUM ('great', 'good', 'okay', 'struggling', 'blocked'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_processing_status') THEN CREATE TYPE event_processing_status AS ENUM ('success', 'failed', 'skipped'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'eng_stage_status') THEN CREATE TYPE eng_stage_status AS ENUM ('not_started', 'in_progress', 'blocked', 'ready_for_review', 'complete'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'eng_task_instance_status') THEN CREATE TYPE eng_task_instance_status AS ENUM ('pending', 'in_progress', 'complete', 'skipped'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'eng_approval_status') THEN CREATE TYPE eng_approval_status AS ENUM ('pending', 'approved', 'rejected'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'counterparty_type') THEN CREATE TYPE counterparty_type AS ENUM ('SUPPLIER', 'INSTALLER', 'OTHER'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'revenue_line_status') THEN CREATE TYPE revenue_line_status AS ENUM ('PLANNED', 'INVOICED', 'PAID', 'IN_BANK', 'REALISED'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'cost_line_status') THEN CREATE TYPE cost_line_status AS ENUM ('PLANNED', 'INVOICED', 'APPROVED', 'PAID'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'pattern_type') THEN CREATE TYPE pattern_type AS ENUM ('PREFIX', 'REGEX', 'TOKEN_SHAPE'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'pattern_match_outcome') THEN CREATE TYPE pattern_match_outcome AS ENUM ('AUTO_APPLIED', 'USER_CONFIRMED', 'USER_OVERRIDDEN', 'UNRESOLVED'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'invoice_capture_status') THEN CREATE TYPE invoice_capture_status AS ENUM ('captured', 'submitted', 'verified', 'approved', 'rejected'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'procurement_category') THEN CREATE TYPE procurement_category AS ENUM ('material', 'equipment', 'service', 'subcontract', 'other'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'procurement_status') THEN CREATE TYPE procurement_status AS ENUM ('requested', 'quoted', 'approved', 'ordered', 'partially_received', 'received', 'invoiced', 'closed'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'procurement_payment_status') THEN CREATE TYPE procurement_payment_status AS ENUM ('not_applicable', 'pending_approval', 'approved', 'scheduled', 'paid', 'on_hold'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tr_rag_status') THEN CREATE TYPE tr_rag_status AS ENUM ('Red', 'Amber', 'Green'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tr_status') THEN CREATE TYPE tr_status AS ENUM ('Active', 'Completed'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tr_link_status') THEN CREATE TYPE tr_link_status AS ENUM ('Linked', 'TaskCreated', 'Done'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tr_suggestion_decision') THEN CREATE TYPE tr_suggestion_decision AS ENUM ('Suggested', 'Accepted', 'Rejected', 'Suppressed'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'row_source') THEN CREATE TYPE row_source AS ENUM ('imported', 'manual', 'imported_edited'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'smart_import_status') THEN CREATE TYPE smart_import_status AS ENUM ('PREVIEW', 'AWAITING_REVIEW', 'COMMITTED', 'ROLLED_BACK', 'FAILED', 'SUPERSEDED'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'import_issue_severity') THEN CREATE TYPE import_issue_severity AS ENUM ('INFO', 'WARNING', 'BLOCKER'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'import_section') THEN CREATE TYPE import_section AS ENUM ('PLAN', 'REVENUE', 'EXPENDITURE', 'CASHFLOW', 'GENERAL'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'import_trigger_type') THEN CREATE TYPE import_trigger_type AS ENUM ('schedule', 'manual', 'webhook'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'import_run_status') THEN CREATE TYPE import_run_status AS ENUM ('running', 'success', 'partial', 'fail'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'change_event_type') THEN CREATE TYPE change_event_type AS ENUM ('created', 'modified', 'deleted', 'renamed'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'import_status_type') THEN CREATE TYPE import_status_type AS ENUM ('pending', 'imported', 'failed', 'skipped'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'change_set_source') THEN CREATE TYPE change_set_source AS ENUM ('IMPORT', 'MANUAL_EDIT', 'OVERRIDE', 'CONFLICT_RESOLUTION', 'PATTERN_LEARNING', 'COUNTERPARTY_UPDATE', 'SYSTEM'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mytool_task_status') THEN CREATE TYPE mytool_task_status AS ENUM ('inbox', 'planned', 'in_progress', 'blocked', 'waiting', 'done', 'cancelled'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mytool_task_priority') THEN CREATE TYPE mytool_task_priority AS ENUM ('low', 'normal', 'high', 'critical'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mytool_priority_horizon') THEN CREATE TYPE mytool_priority_horizon AS ENUM ('today', 'week', 'month', 'quarter'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mytool_priority_severity') THEN CREATE TYPE mytool_priority_severity AS ENUM ('normal', 'important', 'critical'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mytool_priority_status') THEN CREATE TYPE mytool_priority_status AS ENUM ('active', 'monitoring', 'closed', 'not_started', 'in_progress', 'complete'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mytool_recurrence_frequency') THEN CREATE TYPE mytool_recurrence_frequency AS ENUM ('daily', 'weekly', 'monthly'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mytool_task_type') THEN CREATE TYPE mytool_task_type AS ENUM ('task', 'milestone'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mytool_dependency_type') THEN CREATE TYPE mytool_dependency_type AS ENUM ('finish_to_start', 'start_to_start', 'finish_to_finish', 'start_to_finish'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mytool_task_bucket') THEN CREATE TYPE mytool_task_bucket AS ENUM ('project', 'company_ops', 'personal'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'triage_rule_type') THEN CREATE TYPE triage_rule_type AS ENUM ('keyword', 'sender', 'domain'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'phase_source') THEN CREATE TYPE phase_source AS ENUM ('EXCEL_IMPORT', 'MANUAL'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'change_request_type') THEN CREATE TYPE change_request_type AS ENUM ('scope', 'cost', 'schedule', 'technical', 'commercial'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'change_request_status') THEN CREATE TYPE change_request_status AS ENUM ('draft', 'submitted', 'under_review', 'approved', 'rejected', 'implemented', 'closed'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'raid_type') THEN CREATE TYPE raid_type AS ENUM ('risk', 'assumption', 'issue', 'decision'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'raid_status') THEN CREATE TYPE raid_status AS ENUM ('open', 'mitigating', 'resolved', 'closed', 'accepted'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'raid_priority') THEN CREATE TYPE raid_priority AS ENUM ('low', 'medium', 'high', 'critical'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'subcontractor_assignment_status') THEN CREATE TYPE subcontractor_assignment_status AS ENUM ('active', 'completed', 'suspended', 'terminated'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'commissioning_status') THEN CREATE TYPE commissioning_status AS ENUM ('not_started', 'in_progress', 'ready_for_review', 'approved', 'closed'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'evidence_type') THEN CREATE TYPE evidence_type AS ENUM ('document', 'photo', 'form', 'structured_field', 'sign_off', 'linked_record'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'work_item_workstream') THEN CREATE TYPE work_item_workstream AS ENUM ('PD', 'ENG', 'QUALITY', 'PM', 'FINANCE', 'PERSONAL', 'GOVERNANCE'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'work_item_source') THEN CREATE TYPE work_item_source AS ENUM ('SMART_IMPORT', 'UI', 'INTEGRATION', 'SYSTEM'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'work_item_assignment_role') THEN CREATE TYPE work_item_assignment_role AS ENUM ('OWNER', 'ASSIGNEE', 'REVIEWER', 'VIEWER'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'work_item_dep_type') THEN CREATE TYPE work_item_dep_type AS ENUM ('FS', 'SS', 'FF', 'SF'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'task_tag_category') THEN CREATE TYPE task_tag_category AS ENUM ('BUG', 'IMPROVEMENT', 'FEATURE', 'CUSTOM'); END IF;
END
$$;

-- Stub tables: drizzle-kit push will ALTER these to add missing columns
CREATE TABLE IF NOT EXISTS "notifications" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "notification_throttle" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "meeting_summaries" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "meeting_action_items" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "approvals" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "support_tickets" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "feedback_tickets" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "entity_assignments" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "audit_events" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "ee_info_nodes" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "ee_info_edges" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "ee_info_assets" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "ee_info_versions" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "ee_info_settings" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "ee_info_node_details" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "ee_info_node_editors" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "ee_info_node_metrics" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "user_badges" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "user_points" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "teams_chat_groups" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "teams_chat_members" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "teams_chat_messages" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "dashboard_widget_config" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "pm_site_visits" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "pm_on_the_go_actions" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "pm_compliance_tracking" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "pm_mode_preferences" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "ms_accounts" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "ms_objects" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "project_links" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "project_communication_timeline_events" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "communication_follow_ups" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "standup_schedules" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "standup_participants" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "standup_entries" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "domain_events" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "event_subscriptions" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "event_processing_log" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "deliverables" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "deliverable_versions" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "deliverable_files" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "deliverable_events" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "eng_stage_templates" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "eng_task_templates" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "eng_deliverable_templates" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "project_eng_stages" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "project_eng_tasks" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "project_eng_deliverables" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "project_eng_approvals" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "program_expense" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "program_inflows" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "project_plan" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "cashflow_points" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "finance_revenue_monthly" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "finance_cos_monthly" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "working_plan_scenario" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "project_plan_dependency" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "working_plan_dependency_override" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "schedule_change_notice" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "cashflow_weekly_manual" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "cashflow_balance_history" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "available_payment_overrides" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "available_payment_history" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "opex_budget_monthly" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "opex_weekly_manual" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "tracker_monthly_manual" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "payment_terms" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "counterparties" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "counterparty_contacts" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "normalized_revenue_lines" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "normalized_cost_lines" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "invoice_pattern_rules" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "invoice_pattern_matches" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "weekly_reviews" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "tr_items" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "tr_item_project_links" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "tr_item_suggestion_decisions" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "milestone_task_links" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "expense_task_links" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "writeback_mappings" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "writeback_audit_log" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "financial_edit_requests" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "financial_integration_rules" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "invoice_captures" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "procurement_items" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "fye_budgets" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "forecast_pipeline" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "lost_deals" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "fye_kpi_counters" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "fye_report_snapshots" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "sp_settings" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "sp_files" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "import_runs" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "snapshots" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "change_ledger" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "snapshot_metrics" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "sp_file_pointers" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "smart_import_runs" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "import_issues" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "issue_resolution_rules" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "template_profiles" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "mapping_rules" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "normalized_plan_tasks" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "sp_list_config" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "intake_requests" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "intake_task_templates" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "intake_tasks" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "sync_audit_log" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "mock_sp_items" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "change_sets" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "field_changes" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "plan_edit_notifications" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "import_logs" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "manual_edit_flags" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "conflict_resolution_log" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "upload_metadata" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "refresh_logs" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "mytool_tasks" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "mytool_task_dependencies" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "mytool_recurrence_templates" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "mytool_recurrence_instances" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "mytool_timeblocks" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "mytool_daily_reviews" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "mytool_company_priorities" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "priority_links" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "mytool_user_preferences" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "mytool_email_links" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "mytool_dod_templates" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "mytool_settings" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "triage_rules" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "clients" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "project_info" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "project_execution_state" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "project_settings" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "project_phase_history" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "project_rag_audit" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "project_revenue_summary" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "home_notes" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "project_editable_fields" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "pd_tickets" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "calendar_holiday" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "project_team_members" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "phase_template" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "phase_template_item" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "phase_template_item_history" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "phase_template_application" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "merge_audit_log" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "execution_gate_log" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "stage_gate_definitions" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "project_gate_evaluations" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "stage_gate_overrides" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "portfolios" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "portfolio_rollout_plans" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "portfolio_rollout_phases" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "project_portfolio_assignments" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "project_client_history" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "user_project_folders" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "change_requests" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "raid_items" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "derived_project_kpis" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "derived_portfolio_kpis" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "derived_rag_summary" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "scenarios" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "key_date_mappings" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "normalized_execution_phases" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "dashboard_project_metrics" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "dashboard_program_metrics" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "project_handover_gates" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "project_handover_history" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "project_pd_pm_handover" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "project_subcontractor_assignments" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "project_linkage_review_queue" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "qc_template" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "qc_template_phase" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "qc_template_group" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "qc_template_item" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "qc_template_risk_question" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "qc_template_postmortem_metric" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "qc_checklist" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "qc_item_instance" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "qc_item_evidence" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "qc_risk_answer" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "qc_plan_link" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "qc_warning" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "qc_warning_event" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "qc_postmortem" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "qc_postmortem_metric_value" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "qc_postmortem_summary" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "qc_access_challenge" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "commissioning_items" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "evidence_requirement_definitions" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "evidence_collected_items" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "evidence_evaluations" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "evidence_override_records" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "task_comments" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "task_checklists" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "task_checklist_items" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "task_attachments" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "task_deliverables" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "task_activity_log" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "task_watchers" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "work_items" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "work_item_pm" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "work_item_engineering" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "work_item_scheduling" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "work_item_assignments" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "work_item_dependencies" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "work_item_status_history" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "task_tags" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "work_item_tags" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "task_time_entries" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "organizations" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "users" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "error_logs" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "role_credentials" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "app_settings" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "role_permissions" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "user_permission_overrides" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "permission_audit_log" (id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "monthly_report_snapshots" (id SERIAL PRIMARY KEY);
